version: '3.9'

services:
  semarb3_frontend_prod:
    image: ghcr.io/euthal02/semarb3_frontend:latest
    restart: always
    container_name: semarb3_frontend_prod
    volumes:
      - ./app:/app
      - /app/node_modules
      - ./certbot/www/:/var/www/certbot/:ro
    ports:
      - 80:80
  frontend_certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw