version: '3.9'

services:
  semarb3_frontend_dev:
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - 5173:5173
    volumes:
      - ./app:/app
      - /app/node_modules
    container_name: semarb3_frontend_dev
    environment:
      - CHOKIDAR_USEPOLLING=true

