version: '3.9'

services:
  semarb3_frontend_dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - 80:80
    environment:
      - CHOKIDAR_USEPOLLING=true

