version: '3.9'

networks:
  frontend_net:

services:
  semarb3_frontend:
    build:
        dockerfile: 'Dockerfile'
    restart: always
    container_name: semarb3_frontend
    volumes:
      - ./app:/app
    networks:
      frontend_net:
          aliases:
            - semarb3_frontend

  frontend_proxy:
    container_name: frontend_proxy
    restart: always
    image: nginx:1.13.7
    ports:
      - 80:80
    volumes:
      - ./nginx_config/proxy/dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend_net