version: '3.9'

networks:
  frontend_net:

services:
  semarb3_frontend_prod:
    build:
        dockerfile: 'Dockerfile'
    restart: always
    container_name: semarb3_frontend_prod
    volumes:
      - ./app:/app
    networks:
      - frontend_net

  frontend_proxy_prod:
    container_name: frontend_proxy_prod
    restart: always
    image: nginx:1.13.7
    ports:
      - 80:80
    volumes:
      - ./nginx_config/proxy/dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend_net