version: '3.9'
services:
  semarb3_flask_dev:
    container_name: semarb3_flask_dev
    restart: no
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - monitoring-dashboard:/var/tmp
    env_file:
      - path: .env
    depends_on:
      semarb3_db_dev: 
        condition: service_healthy

  semarb3_db_dev:
    image: mysql:5.7
    container_name: semarb3_db_dev
    restart: no
    env_file:
      - path: .env
    ports:
      - 3306:3306
    volumes:
      - semarb3_db_dev:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping -h localhost --user=root --password=root"
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  semarb3_db_dev:
  monitoring-dashboard:
