version: '3.9'
services:
  semarb3_flask_test:
    build:
      context: .
      dockerfile: 'Dockerfile.test'
    environment:
      - SECRET_KEY = 'hallozusammen!4400'
      - DATABASE_URI = 'sqlite:///app.db
      - DASHBOARD_ENABLED = False
    container_name: semarb3_flask_test
    ports:
      - 5000:5000
