version: '3.9'

services:

  semarb3_flask_prod:
    image: ghcr.io/euthal02/semarb3_weatherapi:latest
    build:
      context: .
      dockerfile: 'Dockerfile.prod'
    container_name: semarb3_flask_prod
    environment:
      - DATABASE_URI=mysql+mysqlconnector://root:root@semarb3_db_prod:3306/semarb3_prod
      - SECRET_KEY=hallomarco!8844
      - DASHBOARD_ENABLED=True
    ports:
      - 5000:5000
    volumes:
      - monitoring-prod-dashboard:/var/tmp
    depends_on:
      semarb3_db_prod:
        condition: service_healthy

  semarb3_db_prod:
    image: mysql:5.7
    container_name: semarb3_db_prod
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: semarb3_prod
    healthcheck:
      test: mysqladmin ping -h localhost -uroot --password=$$MYSQL_ROOT_PASSWORD
      start_period: 2s
      interval: 5s
      timeout: 5s
      retries: 55
    ports:
      - 3306:3306
    volumes:
      - semarb3_db_prod:/var/lib/mysql

volumes:
  semarb3_db_prod:
  monitoring-prod-dashboard:
