version: '3.9'
services:
  semarb3_flask_test:
    env_file:
      - path: .env
    build:
      context: .
      dockerfile: 'Dockerfile.test'
    container_name: semarb3_flask_test
    ports:
      - 5000:5000
