version: '3.9'
services:
  semarb3_flask_dev:
    container_name: semarb3_flask_dev
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - monitoring-dashboard:/var/tmp
    environment:
      - DATABASE_URI=mysql+mysqlconnector://root:root@semarb3_db_dev:3306/semarb3_db
      - CHOKIDAR_USEPOLLING=true
      - SECRET_KEY=hallomarco!8844
      - FLASK_DEBUG=1
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - FLASK_APP=app
      - DASHBOARD_ENABLED=True
      - ORGANIZATION = 'org-Vx2q9NIHeJrNCqNTIOZ5C576'
      - PROJECT = 'proj_cdIcvrykTAvgjfS3k3eJSbjX'
      - API_KEY = 'sk-api-user-NuXmGbmdrn02jpyAfptYT3BlbkFJRuPf7ZUuvd8r6NBGmwVi'
      - ASSISTANT_ID = 'asst_AdqTcay6tPbTZi2IWKqxXdvD'
    depends_on:
      semarb3_db_dev: 
        condition: service_healthy

  semarb3_db_dev:
    image: mysql:5.7
    container_name: semarb3_db_dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: semarb3_db
    ports:
      - 3306:3306
    volumes:
      - semarb3_db_dev:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping -h localhost --user=root --password=root"
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  semarb3_db_dev:
  monitoring-dashboard:
