version: '3.9'
services:
  semarb3_flask_test:
    build:
      context: .
      dockerfile: 'Dockerfile.test'
        env_file:
      - path: .env
    container_name: semarb3_flask_test
    ports:
      - 5000:5000
