version: '3.9'
services:
  persistent-flask:
    container_name: persistent_flask_service
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - monitoring-dashboard:/var/tmp
    environment:
      - DATABASE_URI=mysql+mysqlconnector://root:root@msvc-db:3306/msvc
      - CHOKIDAR_USEPOLLING=true
      - SECRET_KEY=hallomarco!8844
      - FLASK_DEBUG=1
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - FLASK_APP=app
      - DASHBOARD_ENABLED=True
    depends_on:
      msvc-db: 
        condition: service_healthy

  msvc-db:
    image: mysql:5.7
    container_name: msvc-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msvc
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping -h localhost --user=root --password=root"
      interval: 5s
      timeout: 5s
      retries: 20
volumes:
  my-db:
  monitoring-dashboard:
