version: '3.9'

services:
  semarb3_frontend_dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    
  nginx:
    image: nginx:alpine
    volumes:
      - /nginx/default.conf /etc/nginx/conf.d/default.conf
    ports:
      - 80:80

